name: PoivronJaune
favicon: null
layout_spectrum: 0.24965
typography_spectrum: 0.78659
title: Le Poivron Jaune - Test and trials
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42039416-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7b00'
    - '#000000'
    - '#7d3d00'
    - '#767676'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
